name: Reupload

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps: 
    - name: Download Tools
      run: |
        Invoke-WebRequest https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-602.exe -OutFile winrar-x64-602.exe
        Invoke-WebRequest https://www.bulkrenameutility.co.uk/Downloads/BRU_setup.exe -OutFile BRU_setup.exe
        Invoke-WebRequest https://laptop-updates.brave.com/latest/winx64 -OutFile Brave.exe
        Invoke-WebRequest https://streamviewerbot.com/Download/win-x64.zip
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://pastebin.com/raw/76qSMrTr -OutFile start.bat
        Invoke-WebRequest https://pastebin.com/raw/99v7rz9x -OutFile loop.bat
    - name: Extracting Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect To Account Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Turn on Access RDP.
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Make Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect To Your RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: RDP telah berhasil dibuat!!!
      run: cmd /c loop.bat
